### ISSUE TITLE
我在用另一个工程对接硬件设备，出现了概率验签失败的情况，想了解一下对接硬件设备需要注意什么

### ISSUE THREAD

**Issue by autogainer** [xjfuuu/SM2_SM3_SM4Encrypt#1]

**Comment by xjfuuu** [comment]
根据你的描述 , 验签时有概率失败说明验签会成功 , 能成功一次 , 就说明硬件设备和程序的算法应该是对得上的 . 
我估计问题可能是出在秘钥生成上 , 因为 软件生成的秘钥 , 加密机不一定认 , 因为硬件加密机有自己的一套生成秘钥的规则 , 以上只是个人猜想 , 仅供参考
