### ISSUE TITLE
sm4填充计算是否有问题？

### ISSUE THREAD

**Issue by 463010817** [xjfuuu/SM2_SM3_SM4Encrypt#10]
sm4填充计算是否有问题？
注释是这样的
//填充:hex必须是32的整数倍填充 ,填充的是80  00 00 00
计算是否需要填充是这样的
int p = 16 - input.length % 16;

但当input.length为32时，p为16，填充完则为48，不是32的整数倍

所以应该做一个判断，p小于16才填充，因为等于16的时候，刚好就是32的整数倍

**Comment by xjfuuu** [comment]
"hex必须是32的整数倍"，这个是表示hex的长度，并不是字节数组的长度。
一个字节可以存储的hex为0x00到0xFF，所以hex长度是32的整数倍，等价于字节数组长度是16的整数倍。

**Comment by 463010817** [comment]
> 

我知道你意思，但我的意思是，数据长度刚好是16的整数倍，按道理应该是不需要填充的，但现在的逻辑是填充16位数据进去了

**Comment by xjfuuu** [comment]
是不是可以这么理解
0x80 是结束符号，是必须要加的，后面的00 00才是填充，然后整体要满足16的整数倍

**Comment by 463010817** [comment]
> 是不是可以这么理解 0x80 是结束符号，是必须要加的，后面的00 00才是填充，然后整体要满足16的整数倍

哦哦，原来是这样，我理解错了，我以为是要填充才要添加0x80 ￣□￣｜｜
