### ISSUE TITLE
SM2解密乱码

### ISSUE THREAD

**Issue by aicccode** [xjfuuu/SM2_SM3_SM4Encrypt#2]
直接clone 下来  执行 SecurityTestAll  ：
--产生SM2秘钥--:
公钥:045da7c8c5666474838e7e0cf63230214cf7547b8ede049a0f7b0a4d5b14f1954017aa9a3bdeb133c5ae3a9ee4460ca3fdff4e95eaae0a3ac62adccdfedd4d91fe
私钥:2bf1ed2fed67adb1b3a8826b98534d1f0d6d605ae28101db02599794b9c2de50
--测试加密开始--
原文UTF-8转hex:49204c6f766520596f7520466f7265766572
加密:
密文:9007e5aeb55ffa5d3fabf95a19e4c07f4a526c462c7418a2bf909cf2d24c7a7e993a3eb6334bedcb0988cc2e2946c80adbf4b9c4554d0073cc7963eecc39821edd3c0d4cb75b6085c35e41bbbbe6a11af0d587f2ee84fbe8794a4f446aecf4d5e246721d6f4f0f7a00eb3aea8b6594d65504
解密:1
\�VHC���i��Ŭ�
--测试加密结束--
--测试SM2签名--
原文hex:49204c6f766520596f7520466f7265766572
签名测试开始:
软加密签名结果:3046022
-------------

**Comment by xjfuuu** [comment]
建议你看一下是不是环境，或者包的错误吧。我刚刚拿你的原文“I Love You Forever”测了一下，是可以用的！测试结果如下：
--产生SM2秘钥--:
公钥:04816214eadd20cba7049fb750de1c3d0cda905fd7739fe2bdc531063a4345be866a564db01f2ad8dca216c0b2579a753194fe53ab4139e32fe91988a36e88a6d2
私钥:1e503974439df92381eb688df42d16bf2a21e8345027444c878417249b0fa01a
--测试加密开始--
原文UTF-8转hex:49204c6f766520596f7520466f7265766572
加密:
密文:66f16622733326f62df9905126f8a8a1dc4669fa56242aa35566e8c1ecc6397eeff6b0be0560aaf071d48df327addc7df871fabb70c4ef41206f58de5d606b45516fba1fc09b4fbf0f66c07b164f619e7553d1f5d8f16c18a79fef633a0f2cf775b9557dfc6f01d6a3347382fe1fb823277f
解密:I Love You Forever
--测试加密结束--
--测试SM2签名--
原文hex:49204c6f766520596f7520466f7265766572
签名测试开始:
软加密签名结果:3044022019cd527202a442b11cb3b4aa4ac3dd3cf1b8560748c53ed396033cbf66bbfcce02206ff6c0e05948f25a4a2c593d067388e61cfb8858aa31fc30825b71890210c419
加密机签名结果:19cd527202a442b11cb3b4aa4ac3dd3cf1b8560748c53ed396033cbf66bbfcce6ff6c0e05948f25a4a2c593d067388e61cfb8858aa31fc30825b71890210c419
验签1,软件加密方式:
软件加密方式验签结果:true
验签2,硬件加密方式:
签名R:19cd527202a442b11cb3b4aa4ac3dd3cf1b8560748c53ed396033cbf66bbfcce
签名S:6ff6c0e05948f25a4a2c593d067388e61cfb8858aa31fc30825b71890210c419
硬件加密方式验签结果:true
--签名测试结束--
--SM3摘要测试--
hash:FA3593F490361C4D0533EC9861DAD8D7D81C5D6BD48FA1F083D5D1272DFF97FB
--SM3摘要结束--
--生成SM4秘钥--
sm4Key:96450933dfcc4205bfd1a70a1ac96362
--生成SM4结束--
--SM4的CBC加密--
密文:a46f2e221c5030fcab6f4a21042d1506f141dc845899da52d060ed8269e9a7d2
CBC解密
解密结果:I Love You Forever
--ECB加密--
ECB密文:31d843548035819e84f3169886702db3d43ef93dc4e3215dea91844bed0b2aae
ECB解密
ECB解密结果:I Love You Forever

**Comment by aicccode** [comment]
OK了，依赖包版本的问题
