### ISSUE TITLE
签名参数问题

### ISSUE THREAD

**Issue by aicccode** [xjfuuu/SM2_SM3_SM4Encrypt#3]
请教一下  前端 [http://www.jonllen.com/upload/jonllen/case/jsrsasign-master/sample-sm2.html](http://www.jonllen.com/upload/jonllen/case/jsrsasign-master/sample-sm2.html)  javascript  SM2的签名   和这里的软签名  如何兼容？

**Comment by xjfuuu** [comment]
这个我之前研究过，不过很久了我已经忘记了，应该是区别不大。只是公钥格式中的头有所不同。你可以看下加密/解密过程的源码，再对照看下SM2算法的具体流程，分析一下。
